alias cfal '$EDITOR ~/.config/alacritty/alacritty.yml'
alias cfi3 '$EDITOR ~/.config/i3/config'
alias cfnvim '$EDITOR ~/.config/nvim'
alias cfpb '$EDITOR -O ~/.config/polybar/config.ini ~/.config/polybar/modules.ini'
alias cfpbm '$EDITOR ~/.config/polybar/modules.ini'
alias cfrr '$EDITOR ~/.config/ranger/rc.conf'
alias cffa '$EDITOR ~/.config/fish/conf.d/alias.fish'

alias dmesg.short 'sudo dmesg -l warn,err'
alias journalctl.short 'sudo journalctl -e -b -1'
alias l 'ls -1a --group-directories-first'
alias la 'ls -la --group-directories-first'
alias lsblk.size 'lsblk -o NAME,FSTYPE,FSVER,LABEL,UUID,FSAVAIL,FSUSED,MOUNTPOINTS'
alias lsize 'ls -1sh'
alias lspci.vga 'lspci -k | grep -A 3 -i -e display -e vga'
alias mount.sf 'sudo mount --mkdir -o uid=sf,gid=users,fmask=113,dmask=002'
alias pacman.update 'sudo pacman -Syu'
alias polybar.restart '~/.config/polybar/restart.sh'
alias r ranger
alias refloginconf 'systemctl kill -s HUP systemd-logind'
alias sudos 'sudo -E'
alias suspend.disable 'systemctl mask --runtime suspend.target'
alias suspend.enable 'systemctl unmask --runtime suspend.target'
alias tm 'tmux a || tmux'
alias xpropi3 'xprop | grep -e WM_CLASS -e WM_NAME'

alias testnvim 'export XDG_CONFIG_HOME=/home/sf/Desktop/example_configs/'
